name: SonarQube Analysis with Quality Gatee

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for better analysis

      # Run SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: sqa_9686e902b78e0492eb4dd1b56ab6aeaa47d42030
          SONAR_HOST_URL: http://44.211.235.140:9000/
        with:
          args: |
            -Dsonar.projectKey=hello1
            -Dsonar.host.url=http://44.211.235.140:9000/

      # Wait for the Quality Gate result
      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5  # Adjust timeout as needed
        env:
          SONAR_TOKEN: sqa_9686e902b78e0492eb4dd1b56ab6aeaa47d42030
          SONAR_HOST_URL: http://44.211.235.140:9000/
